# stats available at
# https://travis-ci.org/strukturag/gstreamer-libde265/
language: c
compiler:
  - clang
  - gcc

env:
  - GSTREAMER=0.10
  - GSTREAMER=1.0

before_install:
  - sudo add-apt-repository -y ppa:strukturag/libde265
  - sh -c "if [ '$GSTREAMER' = '1.0'   ]; then sudo add-apt-repository -y ppa:gstreamer-developers/ppa; fi"
  - sudo apt-get update -qq
  - sudo apt-get install -y libde265-dev gstreamer$GSTREAMER-tools libgstreamer$GSTREAMER-dev libgstreamer-plugins-base$GSTREAMER-dev libgstreamer-plugins-bad$GSTREAMER-dev
  - sh -c "if [ '$GSTREAMER' = '1.0'   ]; then sudo apt-get install -y libgstreamer-plugins-good$GSTREAMER-dev; fi"

install:
  - git clone https://github.com/strukturag/libde265-data.git

script:
  - make GSTREAMER_VERSION=$GSTREAMER
  - LD_LIBRARY_PATH=`pwd` gst-codec-info-$GSTREAMER libgstlibde265.so
  - gst-inspect-$GSTREAMER --gst-plugin-path=`pwd` libgstlibde265.so
  - gst-launch-$GSTREAMER --gst-plugin-path=`pwd` filesrc location=`pwd`/libde265-data/RandomAccess/paris-ra-wpp.bin ! libde265dec mode=raw ! fakesink sync=false
